### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by joaquinvanschoren** [schlegelp/tanglegram#5]
Hi Phillipp, I'd love to try your package, but I'm getting an error on pip install:
```
pip install git+git://github.com/schlegelp/tanglegram@master
...
 ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-bt81skgp/setup.py", line 15, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

Can you please check what is missing here? Thanks!

**Comment by schlegelp** [comment]
Ah apologies for that. I changed setup.py to use setup tools which forgot to commit the `requirements.txt` -_-
Should be fixed now.

**Comment by schlegelp** [comment]
Closing this issue as should be fixed.

**Comment by joaquinvanschoren** [comment]
Sorry, was busy on another project. Thanks!
